spring.application.name=naming-server
server.port=8761
spring.profiles.active=dev
#this is false since naming-server is not a client.
eureka.client.register-with-eureka=false
#this is set to false as naming-server doesn't send any request to any service
eureka.client.fetch-registry=false
#this setting is configured since the naming-server will be running as standalone (single-node)
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname:localhost}:${server.port}/eureka/

# Health Check
management.endpoint.health.show-details=always

# Config server
spring.config.import=optional:configserver:http://${CONFIG_SERVER_NAME:config-server}:${CONFIG_SERVER_PORT:8888}