server.port= 8081
hello.message= "Hello PROD from Centralized Config Server!"
eureka.instance.prefer-ip-address= true
eureka.instance.hostname= ${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.client.service-url.defaultZone= http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/
management.endpoints.web.exposure.include= "*"