spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/Erenkta/telco-crm.git
spring.cloud.config.server.git.default-label=main
# I will create a folder for each service under the config-files
spring.cloud.config.server.git.search-paths=config-files/*
# To make initialization eager. Issues will be catch in startup
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.fail-fast=true